spring:
  thymeleaf:
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: "/static/**"
  port: 8080
logging:
  level:
    root: info
    org.springframework.web: info
